platform :ios, '15.1'

use_frameworks! :linkage => :static

pod 'Firebase'
pod 'FirebaseCoreInternal'
pod 'GoogleUtilities'
pod 'FirebaseCore'

def node_require(script)
  require Pod::Executable.execute_command(
    'node',
    ['-p', "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]
  ).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

prepare_react_native_project!

target 'settisfy' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

  # ✅ MUST BE INSIDE THE TARGET
  setup_permissions([
    'LocationAccuracy',
    'LocationAlways',
    'LocationWhenInUse',
    'Camera',
    'PhotoLibrary',
    'Notifications'
  ])

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
